#!/usr/bin/env bash

set -e

cd "$(dirname "$0")"

mkdir -p ~/workspace

./brew.sh

/usr/local/opt/fzf/install

cp .bash_profile ~/.bash_profile

git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it

echo "Installing bash-it"
~/.bash_it/install.sh

source ~/.bash_profile --silent

./bash-it-config.sh

git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime
sh ~/.vim_runtime/install_awesome_vimrc.sh

# TODO: figure out how to set below (default color scheme is okay for now)
# Set theme to darkblue for vim
#sed -i -e 's/solarized/darkblue' ~/.vimrc.local

./git.sh

if [[ "$(uname -s)" == Darwin* ]]; then
    ./osx.sh
fi

echo "Finished"
echo "Install Chrome https://www.google.com/chrome/"
echo "Ad blocker for chrome https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm"
echo "Json formatter for chrome https://chrome.google.com/webstore/detail/json-formatter/bcjindcccaagfpapjjmafapmmgkkhgoa?hl=en-US"
echo "Setup go2shell https://superuser.com/questions/434660/how-to-open-go2shell-preferences-in-mac-osx"
echo "Setup Alfred"
echo "Install Slack https://slack.com/downloads\n"

echo "Useful Jetbrains plugins"
echo "String Manipulation"
echo "Bitbucket Linky"
echo "JPA Buddy"
echo "Randomness"
echo "UUID Generator"
echo "Rainbow Brackets"
echo "SonarLint"
echo "SQL Formatter"
